Repository AGH-Narzedzia-Informatyczne-2022-2023/majestic-dreamers, pull requests merged in 2022-11, with the labels that each got.

#9 Create szachy.cbp
  szachy.cbp
Labels: invalid

#8 Added apple loop
  loop.py
Labels: feature, important

#10 moje zmiany do gry
  zmiany_do_snaka/waz.py
Labels: feature

#11 Snake example code
  rogake/main.py
Labels: feature

#12 Fib w Py
  .vs/ProjectSettings.json
  .vs/VSWorkspaceState.json
  .vs/majestic-dreamers/FileContentIndex/1cae7f90-4a52-481d-a0e9-dff6a58659f4.vsidx
  .vs/majestic-dreamers/FileContentIndex/c0a79c98-ca37-4fe8-8f2c-9b1d9dbcc0fb.vsidx
  .vs/majestic-dreamers/FileContentIndex/read.lock
  .vs/majestic-dreamers/v17/.suo
  .vs/slnx.sqlite
  waz/fib.py
  waz/waz.pyproj
Labels: feature

#13 feat: add a logo
  art/logo.png
Labels: feature, important
